packages:
  - 'icons'
  - 'docs'
overrides:
  sass-embedded: 1.100.0

allowBuilds:
  '@carbon/icons': true
  '@carbon/pictograms': true
  '@parcel/watcher': true
  '@vaadin/vaadin-usage-statistics': true
  core-js: true
  es5-ext: true
  esbuild: true
  ttf2woff2: false

minimumReleaseAge: 0
trustLockfile: true
